# Joint limits

joint_limits:
  joint_1:
    min_position: !degrees -180
    max_position: !degrees  180
    max_velocity: !degrees  175
    max_effort: 1000.0

  joint_2:
    min_position: !degrees  -90
    max_position: !degrees  150
    max_velocity: !degrees  175
    max_effort: 1000.0

  joint_3:
    min_position: !degrees -180
    max_position: !degrees   75
    max_velocity: !degrees  175
    max_effort: 1000.0

  joint_4:
    min_position: !degrees -400
    max_position: !degrees  400
    max_velocity: !degrees  250
    max_effort: 1000.0

  joint_5:
    min_position: !degrees -125
    max_position: !degrees  120
    max_velocity: !degrees  250
    max_effort: 1000.0

  joint_6:
    min_position: !degrees -400
    max_position: !degrees  400
    max_velocity: !degrees  360
    max_effort: 1000.0
